server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_orm_test?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: fangbowen2000

mybatis:
  type-aliases-package: tech.pdai.springboot.mysql57.anno.entity
  configuration:
    cache-enabled: true # 开启二级缓存，启用后可提高查询效率，减少数据库访问次数
    use-generated-keys: true # 允许 JDBC 支持自动生成主键，需要驱动兼容
    default-executor-type: REUSE # 配置默认的执行器，REUSE 执行器会重用预处理语句
    use-actual-param-name: true # 允许使用方法签名中的名称作为参数名称，便于调试和日志记录

knife4j:
  enable: true
  setting:
    # default lang
    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT | [Java 全栈](https://pdai.tech)
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models
